Iter18
AsakoKabe/go-yandex-shortener pull request #17
Opened 2024-08-20 14:19 UTC by AsakoKabe

2024-08-25 14:09 UTC, AsakoKabe commented
Проблема с линтера из-за того, что меняли версию го (исходя из того, что написано в пачке). Как напишут, что надо сделать - исправлю

2024-08-27 22:24 UTC, avhitrov requested changes
Комментарии по коду ок. Pprof ok. Есть предложение причесать все импорты. По поводу несходящегося теста (govet) обещали исправить, в любом случае не блокер.

2024-08-27 22:24 UTC, avhitrov commented on internal/app/server/handlers/handler.go
>  	"github.com/AsakoKabe/go-yandex-shortener/internal/logger"
Пришло время причесать импорты во всем коде в соответствии с рекомендациями goimports (gofumpt)
https://t.me/bushigo/27
(по ссылке есть хинт для VS Code)

2024-08-29 21:32 UTC, avhitrov approved these changes
Все отлично!

2024-08-30 10:29 UTC, merged